- name: ssh # match with name in host.d/example.com.yml
  modules:
  - name: "POODLE Scanner" # arbitrary
    cronspec: "@every 1d"
    commands:
    - "use auxiliary/scanner/http/ssl_version"
    - "set RHOSTS SPLOITHOSTNAME" # SPLOITHOSTNAME will be subbed at runtime
    - "set RPORT SPLOITHOSTPORT" # SPLOITHOSTPORT will be subbed at runtime
    - "set SSLVersion SSL3"
    - "run"
  - name: "blahditty" # arbitrary
    cronspec: "30 * * * *"
    commands:
    - "use auxiliary/ssh/blahdittyblah"
    - "set RHOST SPLOITHOSTNAME" # SPLOITHOSTNAME will be subbed at runtime
    - "set RPORT SPLOITHOSTPORT" # SPLOITHOSTPORT will be subbed at runtime
    - "set SSLVersion SSL3"
    - "run"

- name: nginx # match with name in host.d/example.com.yml
  modules:
  - name: "nginx" # arbitrary
    cronspec: "30 * * * *"
    commands:
    - "use auxiliary/nginx/testing123"
    - "set RHOST SPLOITHOSTNAME" # SPLOITHOSTNAME will be subbed at runtime
    - "set RPORT SPLOITHOSTPORT" # SPLOITHOSTPORT will be subbed at runtime
    - "set SSLVersion SSL3"
    - "run"

- name: nginxssl # match with name in host.d/example.com.yml
  modules:
  - name: "nginxssl" # arbitrary
    cronspec: "30 * * * *"
    commands:
    - "use auxiliary/nginxssl/ssl"
    - "set RHOST SPLOITHOSTNAME" # SPLOITHOSTNAME will be subbed at runtime
    - "set RPORT SPLOITHOSTPORT" # SPLOITHOSTPORT will be subbed at runtime
    - "set SSLVersion SSL3"
    - "run"

- name: rails # match with name in host.d/example.com.yml
  modules:
  - name: "railsssl" # arbitrary
    cronspec: "30 * * * *"
    commands:
    - "use auxiliary/rails/railsssl"
    - "set RHOST SPLOITHOSTNAME" # SPLOITHOSTNAME will be subbed at runtime
    - "set RPORT SPLOITHOSTPORT" # SPLOITHOSTPORT will be subbed at runtime
    - "set SSLVersion SSL3"
    - "run"

- name: postgres # match with name in host.d/example.com.yml
  modules:
  - name: "postgres" # arbitrary
    cronspec: "30 * * * *"
    commands:
    - "use auxiliary/postgres/blahello"
    - "set RHOST SPLOITHOSTNAME" # SPLOITHOSTNAME will be subbed at runtime
    - "set RPORT SPLOITHOSTPORT" # SPLOITHOSTPORT will be subbed at runtime
    - "set SSLVersion SSL3"
    - "run"
